apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: fiap-contato
spec:
  selector:
    app: grafana
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 31004
  type: NodePort
