apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: fiap-contato
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 31003
  type: NodePort
