apiVersion: v1
kind: Service
metadata:
  name: fiap-contato-mysql
  namespace: fiap-contato
spec:
  selector:
    app: fiap-contato-mysql-statefulset
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 31000
    protocol: TCP
    name: mysql
  type: NodePort
