CREATE DATABASE FIAPContato;

CREATE TABLE FIAPContato.Contato 
(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    DDD VARCHAR(2) NOT NULL,
    Telefone VARCHAR(15) NOT NULL,
    Email VARCHAR(100) NOT NULL
);