apiVersion: v1
kind: Service
metadata:
  name: fiap-contato-consumer-service
  labels:
    app: fiap-contato-consumer
spec:
  selector:
    app: fiap-contato-consumer
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
