apiVersion: v1
kind: ConfigMap
metadata:
  name: fiap-contato-config
  namespace: fiap-contato
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  DOTNET_ENVIRONMENT: "Development"
  Connection_String: "Server=fiap-contato-mysql.fiap-contato.svc.cluster.local;Database=FIAPContato;"
  MassTransit_Servidor: "fiap-contato-rabbitmq.fiap-contato.svc.cluster.local"
  MassTransit_Usuario: "guest"
  MassTransit_Senha: "guest"
  MassTransit_Filas_ContatoFila: "contato-queue"
  my.cnf: |
    [mysqld]
    bind-address=0.0.0.0
  init-scripts: |
    CREATE DATABASE IF NOT EXISTS FIAPContato;
    USE FIAPContato;
    CREATE TABLE IF NOT EXISTS Contato (
      ID INT AUTO_INCREMENT PRIMARY KEY,
      Nome VARCHAR(100) NOT NULL,
      DDD VARCHAR(2) NOT NULL,
      Telefone VARCHAR(15) NOT NULL,
      Email VARCHAR(100) NOT NULL
    );
