apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
  annotations:
    description: "RabbitMQ"
    owner: "Rodrigo"
    version: "1.0.0"
spec:
  replicas: 1
  selector:

    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: masstransit/rabbitmq
        ports:
        - containerPort: 5672
        - containerPort: 15672
