#comando enconde - echo 'FIAPContato' | base64
#comando decode -  base64 -d <<< MjAyNDA2
apiVersion: v1
kind: Secret
metadata:
  name: fiap-contato-secret
  namespace: fiap-contato
type: Opaque
data:
  MYSQL_USER: cm9vdAo=
  MYSQL_ROOT_PASSWORD: MjAyNDA2
  MYSQL_PASSWORD: MjAyNDA2Cg==
