apiVersion: v1
kind: Service
metadata:
  name: fiap-contato-api-service
  namespace: fiap-contato
spec:
  type: NodePort
  selector:
    app: fiap-contato-api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31001
