apiVersion: v1
kind: Service
metadata:
  name: fiap-contato-rabbitmq
  namespace: fiap-contato
spec:
  type: NodePort
  selector:
    app: fiap-contato-rabbitmq-deployment
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: amqp2
    protocol: TCP
    port: 15672
    targetPort: 15672
    nodePort: 31002
